version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /host/synology
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /training
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /training/validation
    schedule:
      interval: daily
